### ISSUE TITLE
ReadMe

### ISSUE THREAD

**Issue by MathiasAugustto** [JGhostM/Landing-Page-AdvenTours-TF#1]
En el apartado de redirigir con tan solo hacer click en el Menu del Landing Page (MODIFICAR o Agregar ) líneas de código para solucionar dicho problema.

**Comment by MathiasAugustto** [comment]
Por favor, debemos agregar la información faltante dentro de la Landing Page (dejar comentarios para modificar dicho problema/inconveniente)

**Comment by JGhostM** [comment]
thanks
